/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 06-mar-2012, 21:37:07
 */
package ProyectoDeGrado;

import panamahitek.Arduino.PanamaHitek_Arduino;
import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import org.apache.commons.codec.binary.Base64;
import static ProyectoDeGrado.LoginPassCam.IP_CAM;



/**
 *
 * @author Rolando
 * 
 */
public class VentanaPrincipal extends javax.swing.JFrame {
  
    ControlCamara controlCamara;
    Arduino arduino;
    
    public VentanaPrincipal() {
    
        controlCamara= new ControlCamara();
        arduino = new Arduino();
        initComponents();
        setTitle("Visor de Cámaras IP");
        setResizable(false);
        setLocationRelativeTo(null);
        KeyListener listener = new MyKeyListener();
        addKeyListener(listener);
        setFocusable(true);  
    }
   
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConectarCamara = new javax.swing.JButton();
        panelVideo = new ProyectoDeGrado.PanelCamara();
        Arriba = new javax.swing.JButton();
        Abajo = new javax.swing.JToggleButton();
        Izquierda = new javax.swing.JToggleButton();
        Derecha = new javax.swing.JToggleButton();
        EstadoInicial = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Puertos = new javax.swing.JComboBox();
        ConecArduino = new javax.swing.JToggleButton();
        DesconArduino = new javax.swing.JToggleButton();
        ArribaRobot = new javax.swing.JButton();
        IzquierdaRobot = new javax.swing.JToggleButton();
        DerechaRobot = new javax.swing.JToggleButton();
        AbajoRobot = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        botonConectarCamara.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        botonConectarCamara.setForeground(new java.awt.Color(0, 0, 153));
        botonConectarCamara.setText("Conectar a cámara IP");
        botonConectarCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarCamaraActionPerformed(evt);
            }
        });

        panelVideo.setMaximumSize(new java.awt.Dimension(640, 352));
        panelVideo.setMinimumSize(new java.awt.Dimension(640, 352));
        panelVideo.setPreferredSize(new java.awt.Dimension(640, 352));

        javax.swing.GroupLayout panelVideoLayout = new javax.swing.GroupLayout(panelVideo);
        panelVideo.setLayout(panelVideoLayout);
        panelVideoLayout.setHorizontalGroup(
            panelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        panelVideoLayout.setVerticalGroup(
            panelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        Arriba.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        Arriba.setText("Arriba");
        Arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArribaActionPerformed(evt);
            }
        });

        Abajo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Abajo.setText("Abajo");
        Abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbajoActionPerformed(evt);
            }
        });

        Izquierda.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Izquierda.setText("Izquierda");
        Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzquierdaActionPerformed(evt);
            }
        });

        Derecha.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Derecha.setText("Derecha");
        Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerechaActionPerformed(evt);
            }
        });

        EstadoInicial.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        EstadoInicial.setText("Estado inicial");
        EstadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoInicialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setText("Control de cámara");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel2.setText("Control del robot");

        jLabel3.setText("Seleccione el puerto:");

        Puertos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM10", "COM11", "COM12", "COM13", "COM14", "COM15", "COM16", "COM17", "COM18" }));
        Puertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuertosActionPerformed(evt);
            }
        });

        ConecArduino.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        ConecArduino.setText("Conectar");
        ConecArduino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConecArduinoActionPerformed(evt);
            }
        });

        DesconArduino.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        DesconArduino.setText("Desconectar");
        DesconArduino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesconArduinoActionPerformed(evt);
            }
        });

        ArribaRobot.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        ArribaRobot.setText("↑");
        ArribaRobot.setBorderPainted(false);
        ArribaRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArribaRobotActionPerformed(evt);
            }
        });

        IzquierdaRobot.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        IzquierdaRobot.setText("←");
        IzquierdaRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzquierdaRobotActionPerformed(evt);
            }
        });

        DerechaRobot.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        DerechaRobot.setText("→");
        DerechaRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerechaRobotActionPerformed(evt);
            }
        });

        AbajoRobot.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        AbajoRobot.setText("↓");
        AbajoRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbajoRobotActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel4.setText("Conexión del robot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(panelVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConecArduino)
                                .addGap(28, 28, 28)
                                .addComponent(DesconArduino))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Puertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(IzquierdaRobot)
                                    .addGap(56, 56, 56)
                                    .addComponent(DerechaRobot))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AbajoRobot)
                                        .addComponent(ArribaRobot))
                                    .addGap(50, 50, 50)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(botonConectarCamara)
                        .addGap(111, 111, 111)
                        .addComponent(Izquierda)
                        .addGap(12, 12, 12)
                        .addComponent(EstadoInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Derecha))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(Arriba))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(Abajo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ArribaRobot)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IzquierdaRobot)
                            .addComponent(DerechaRobot))
                        .addGap(18, 18, 18)
                        .addComponent(AbajoRobot)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Puertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConecArduino)
                            .addComponent(DesconArduino))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(Arriba)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoInicial)
                    .addComponent(Izquierda)
                    .addComponent(Derecha)
                    .addComponent(botonConectarCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(Abajo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonConectarCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarCamaraActionPerformed

    
    panelVideo.setDireccionIP(IP_CAM);    
    panelVideo.setHayConexion(true);
    panelVideo.repaint();
    this.requestFocus(); //La ventana principal vuelve a requerir el foco
    
}//GEN-LAST:event_botonConectarCamaraActionPerformed
/*   @Autor Victor Cruz y Sergio Echeverry
            Se crean botones para mover la cámara IP
*/
    private void ArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArribaActionPerformed
        // TODO add your handling code here:
       
         
       controlCamara.arriba();
       this.requestFocus(); //La ventana principal vuelve a requerir el foco
      
      
        
       // panelVideo.repaint();
    }//GEN-LAST:event_ArribaActionPerformed

    private void IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzquierdaActionPerformed
        // TODO add your handling code here:
        controlCamara.izquierda();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
    }//GEN-LAST:event_IzquierdaActionPerformed

    private void DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerechaActionPerformed
        // TODO add your handling code here:
        controlCamara.derecha();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
    }//GEN-LAST:event_DerechaActionPerformed

    private void EstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoInicialActionPerformed
      
        controlCamara.estadoInicial();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
    }//GEN-LAST:event_EstadoInicialActionPerformed

    private void AbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbajoActionPerformed
        //://
// TODO add your handling code here:
        controlCamara.abajo();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
       
    }//GEN-LAST:event_AbajoActionPerformed

    private void PuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuertosActionPerformed
      

    }//GEN-LAST:event_PuertosActionPerformed

    private void ConecArduinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConecArduinoActionPerformed

        arduino.conecArduino();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco

    }//GEN-LAST:event_ConecArduinoActionPerformed

    private void DesconArduinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesconArduinoActionPerformed
        
        arduino.desconArduino();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
    }//GEN-LAST:event_DesconArduinoActionPerformed

    private void ArribaRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArribaRobotActionPerformed

        arduino.arribaRobot();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
    
    }//GEN-LAST:event_ArribaRobotActionPerformed

    private void IzquierdaRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzquierdaRobotActionPerformed
        
        arduino.izquierdaRobot();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
      
    }//GEN-LAST:event_IzquierdaRobotActionPerformed

    private void DerechaRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerechaRobotActionPerformed
        
        arduino.derechaRobot();
        this.requestFocus(); //La ventana principal vuelve a requerir el foco
    }//GEN-LAST:event_DerechaRobotActionPerformed

    private void AbajoRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbajoRobotActionPerformed

        arduino.abajoRobot();
        this.requestFocus();
    }//GEN-LAST:event_AbajoRobotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaPrincipal().setVisible(true);
                 
                 
                 
                
            }
            
            
        });
    }

    
    public class MyKeyListener implements KeyListener{

        @Override
        public void keyTyped(KeyEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void keyPressed(KeyEvent e) {
            
            switch(e.getKeyCode()){
                case KeyEvent.VK_ENTER:
                    botonConectarCamaraActionPerformed(null);                    
                    break;
                    
                case KeyEvent.VK_W:
                    ArribaActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_A:
                    IzquierdaActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_D:
                    DerechaActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_S:
                    AbajoActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_H:
                    EstadoInicialActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_UP:
                    ArribaRobotActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_DOWN:
                    AbajoRobotActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_RIGHT:
                    DerechaRobotActionPerformed(null);
                    break;
                    
                case KeyEvent.VK_LEFT:
                    IzquierdaRobotActionPerformed(null);
                    
                    break;
                                                                                 
            }
                
            
            
        }

        @Override
        public void keyReleased(KeyEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Abajo;
    private javax.swing.JToggleButton AbajoRobot;
    private javax.swing.JButton Arriba;
    private javax.swing.JButton ArribaRobot;
    private javax.swing.JToggleButton ConecArduino;
    private javax.swing.JToggleButton Derecha;
    private javax.swing.JToggleButton DerechaRobot;
    private javax.swing.JToggleButton DesconArduino;
    private javax.swing.JToggleButton EstadoInicial;
    private javax.swing.JToggleButton Izquierda;
    private javax.swing.JToggleButton IzquierdaRobot;
    public static javax.swing.JComboBox Puertos;
    private javax.swing.JButton botonConectarCamara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private ProyectoDeGrado.PanelCamara panelVideo;
    // End of variables declaration//GEN-END:variables
}
